/*
 * Topic: Queue Applications
 *
 * Practical examples demonstrating how a queue
 * can be used to solve common programming and
 * embedded-system problems.
 *
 * Applications:
 *
 * 1. Store and process SensorData in arrival order
 * 2. Process system events
 * 3. Process commands in FIFO order
 * 4. Simulate a UART packet queue
 *
 * Concepts covered:
 *
 * - FIFO (First In First Out)
 * - Generic programming with templates
 * - Custom data types
 * - Event processing
 * - Command processing
 * - Buffered communication
 */

#include "queue_template.hpp"
#include <iostream>

using namespace std;


/*
 * Example custom sensor data type.
 */
struct SensorData
{
    int sensorId;
    float value;
    unsigned long timestamp;
};


/*
 * Example event type.
 *
 * Events are typically generated by
 * different parts of an embedded system
 * and processed later by another module.
 */
enum EventType
{
    BUTTON_PRESSED,
    SENSOR_READY,
    MOTOR_STARTED,
    MOTOR_STOPPED
};

struct SystemEvent
{
    EventType type;
    unsigned long timestamp;
};


/*
 * Example command type.
 */
struct Command
{
    int commandId;
    int parameter;
};


/*
 * Example communication packet.
 */
struct UartPacket
{
    int packetId;
    char payload;
};



int main()
{

/******************************************************************************
 * Example 1:
 * Store and process SensorData in FIFO order
 ******************************************************************************/

    Queue<SensorData> sensorQueue;
    SensorData sensor;

    for (int i = 0; i < 5; i++)
    {
        sensor.sensorId = i + 1;
        sensor.value = 20.0f + i;
        sensor.timestamp = 1000 + i;

        sensorQueue.enqueue(sensor);
    }

    cout << "Sensor Queue:\n";

    while (sensorQueue.dequeue(sensor))
    {
        cout << "Sensor " << sensor.sensorId << " | Value: " << sensor.value << " | Timestamp: " << sensor.timestamp
             << "\n";
    }

    cout << "\n";


/******************************************************************************
 * Example 2:
 * Process system events
 *
 * Events are processed in the same
 * order in which they were generated.
 ******************************************************************************/

    Queue<SystemEvent> eventQueue;

    eventQueue.enqueue({BUTTON_PRESSED, 2000});
    eventQueue.enqueue({SENSOR_READY, 2010});
    eventQueue.enqueue({MOTOR_STARTED, 2020});
    eventQueue.enqueue({MOTOR_STOPPED, 2500});

    SystemEvent event;

    cout << "System Events:\n";

    while (eventQueue.dequeue(event))
    {
        cout << "Event Type: " << event.type << " | Timestamp: " << event.timestamp << "\n";
    }

    cout << "\n";


/******************************************************************************
 * Example 3:
 * Process commands in FIFO order
 *
 * The first command received
 * is also the first command executed.
 ******************************************************************************/

    Queue<Command> commandQueue;

    commandQueue.enqueue({1, 100});
    commandQueue.enqueue({2, 200});
    commandQueue.enqueue({3, 300});

    Command command;

    cout << "Command Queue:\n";

    while (commandQueue.dequeue(command))
    {
        cout << "Command ID: " << command.commandId << " | Parameter: " << command.parameter << "\n";
    }

    cout << "\n";


/******************************************************************************
 * Example 4:
 * Simulate buffered UART packet processing
 *
 * Packets are received first and processed
 * later in exactly the same order.
 ******************************************************************************/

    Queue<UartPacket> uartQueue;

    uartQueue.enqueue({1, 'A'});
    uartQueue.enqueue({2, 'B'});
    uartQueue.enqueue({3, 'C'});
    uartQueue.enqueue({4, 'D'});

    UartPacket packet;

    cout << "UART Packet Queue:\n";

    while (uartQueue.dequeue(packet))
    {
        cout << "Packet " << packet.packetId << " | Payload: " << packet.payload << "\n";
    }

    return 0;
}
